- name: Web Server Construction
  hosts: all
  tasks:
    - name: install web server
      yum:
        name: "{{ package }}"
        state: latest
      when: inventory_hostname in groups['webserver']

    - name: install database server
      yum:
        name: "{{ package }}"
        state: latest
      when: inventory_hostname in groups['dbserver']

    - name: start httpd
      systemd:
        name: "{{ service }}"
        state: started
        enabled: true
      when: inventory_hostname in groups['webserver']

    - name: start mariadb
      systemd:
        name: "{{ service }}"
        state: started
        enabled: true
      when: inventory_hostname in groups['dbserver']
